name = "SimpleSolvers"
uuid = "36b790f5-6434-4fbe-b711-1f64a1e2f6a2"
version = "0.7.7"
authors = ["Michael Kraus"]

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometricBase = "9a0b12b7-583b-4f04-aa1f-d8551b6addc9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distances = "0.10"
ForwardDiff = "0.10, 1"
GeometricBase = "0.12.7, 0.13"
NaNMath = "1"
Random = "1"
SafeTestsets = "0.1.0"
StaticArrays = "1.9.13"
julia = "1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "NaNMath", "SafeTestsets", "Test", "Random"]
