name: Documentation

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages for generating tikz images
        run: |
          sudo apt-get install imagemagick
          sudo apt-get install poppler-utils
          sudo apt-get install texlive-xetex
          sudo apt-get install texlive-science
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Make tikz images
        run: make all -C docs/src/trust_region
      - name: Set environment variables
        run: echo "PYTHON=''" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.build()
            Pkg.precompile()'
      - name: Run doctests
        run: |
          julia --project=docs -e '
            using Documenter: doctest
            using SimpleSolvers
            doctest(SimpleSolvers)'
      - name: Build and deploy Documentation
        run: julia --project make.jl
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
